# Generated by Django 2.0.4 on 2018-04-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='toppic_data_to_use/'),
        ),
    ]
